/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import db.KoneksiDatabase;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIKI HENDRIYANTO
 */
public class ViewListDataMobil extends javax.swing.JFrame {
    private ViewPeminjamanMobil VP;
    private DefaultTableModel tbmodel;
    
    /**
     * Creates new form ViewListDataPelanggan
     */
    public ViewListDataMobil(ViewPeminjamanMobil VP) {
        initComponents();
        
        this.VP = VP;
        
        tbmodel = new DefaultTableModel();
        TBListDataMobil.setModel(tbmodel);
        tbmodel.addColumn("ID Mobil");
        tbmodel.addColumn("Merek");
        tbmodel.addColumn("Tipe");
        tbmodel.addColumn("Tahun");
        tbmodel.addColumn("No Polisi");
        tbmodel.addColumn("Harga");
        tampilDataMobil();
    }
    
    public void tampilDataMobil(){
        
        tbmodel.getDataVector().removeAllElements();
        tbmodel.fireTableDataChanged();
        
        //Query untuk menampilkan data mobil yang belum atau sedang tidak dipinjam
        String sql = "SELECT mobil.*"
                + " FROM mobil"
                + " LEFT JOIN peminjaman ON mobil.id_mobil = peminjaman.id_mobil"
                + " WHERE peminjaman.status is null OR peminjaman.status = 'Kembali'"
                + " ORDER by mobil.merek";
        
        try {
            Statement stat = (Statement) KoneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                Object[] hasil;
                hasil = new Object[6]; 
                hasil[0] = res.getString("id_mobil");
                hasil[1] = res.getString("merek");
                hasil[2] = res.getString("tipe");
                hasil[3] = res.getString("tahun");
                hasil[4] = res.getString("no_polisi");
                hasil[5] = res.getString("harga");
                
                tbmodel.addRow(hasil);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBListDataMobil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Mobil");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("DATA MOBIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TBListDataMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBListDataMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBListDataMobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBListDataMobil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(725, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TBListDataMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBListDataMobilMouseClicked
        // TODO add your handling code here:
        int listX = TBListDataMobil.getSelectedRow();
        VP.getTFIdMobil().setText(TBListDataMobil.getValueAt(listX,0).toString());
        VP.getTFMerek().setText(TBListDataMobil.getValueAt(listX,1).toString());
        VP.getTFTipe().setText(TBListDataMobil.getValueAt(listX,2).toString());
        VP.getTFTahun().setText(TBListDataMobil.getValueAt(listX,3).toString());
        VP.getTFNoPolisi().setText(TBListDataMobil.getValueAt(listX,4).toString());
        VP.getTFHargaSewa().setText(TBListDataMobil.getValueAt(listX,5).toString());
        
        dispose();
    }//GEN-LAST:event_TBListDataMobilMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBListDataMobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
