/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc;

import view.ViewLaporanPeminjaman;
import view.ViewLogin;
import view.ViewMobil;
import view.ViewPelanggan;
import view.ViewPeminjamanMobil;
import view.ViewPengembalianMobil;

/**
 *
 * @author DIKI HENDRIYANTO
 */
public class MenuUtama_Karyawan extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiUtama
     */
    public MenuUtama_Karyawan() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BTMenuPelanggan = new javax.swing.JButton();
        BTMenuMobil = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BTMenuTransaksi = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BTMenuLaporanPeminjaman = new javax.swing.JButton();
        BTMenuPengembalian = new javax.swing.JButton();
        BTMenuUser = new javax.swing.JButton();
        BTLogout = new javax.swing.JButton();
        DPMenuUtama = new javax.swing.JDesktopPane();
        menuUtamaBackground1 = new background.MenuUtamaBackground();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Rental Mobil");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("GC Rent. ");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Menu");

        BTMenuPelanggan.setBackground(new java.awt.Color(204, 204, 204));
        BTMenuPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTMenuPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/IconData.png"))); // NOI18N
        BTMenuPelanggan.setText("Master Pelanggan");
        BTMenuPelanggan.setEnabled(false);
        BTMenuPelanggan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTMenuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMenuPelangganActionPerformed(evt);
            }
        });

        BTMenuMobil.setBackground(new java.awt.Color(204, 204, 204));
        BTMenuMobil.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTMenuMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/IconData.png"))); // NOI18N
        BTMenuMobil.setText("Master Mobil");
        BTMenuMobil.setEnabled(false);
        BTMenuMobil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTMenuMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMenuMobilActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Master Data");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Transaksi ");

        BTMenuTransaksi.setBackground(new java.awt.Color(204, 204, 204));
        BTMenuTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTMenuTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/IconTransaksi.png"))); // NOI18N
        BTMenuTransaksi.setText("Peminjaman Mobil");
        BTMenuTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTMenuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMenuTransaksiActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Laporan");

        BTMenuLaporanPeminjaman.setBackground(new java.awt.Color(204, 204, 204));
        BTMenuLaporanPeminjaman.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTMenuLaporanPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/IconReport.png"))); // NOI18N
        BTMenuLaporanPeminjaman.setText("Laporan Peminjaman");
        BTMenuLaporanPeminjaman.setEnabled(false);
        BTMenuLaporanPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTMenuLaporanPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMenuLaporanPeminjamanActionPerformed(evt);
            }
        });

        BTMenuPengembalian.setBackground(new java.awt.Color(204, 204, 204));
        BTMenuPengembalian.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTMenuPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/IconTransaksi.png"))); // NOI18N
        BTMenuPengembalian.setText("Pengembalian Mobil");
        BTMenuPengembalian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTMenuPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMenuPengembalianActionPerformed(evt);
            }
        });

        BTMenuUser.setBackground(new java.awt.Color(204, 204, 204));
        BTMenuUser.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTMenuUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/IconData.png"))); // NOI18N
        BTMenuUser.setText("Master User");
        BTMenuUser.setEnabled(false);
        BTMenuUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTMenuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMenuUserActionPerformed(evt);
            }
        });

        BTLogout.setBackground(new java.awt.Color(204, 204, 204));
        BTLogout.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/IconLogout.png"))); // NOI18N
        BTLogout.setText("Logout");
        BTLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BTLogout)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(BTMenuUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTMenuPengembalian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTMenuMobil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTMenuPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTMenuTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTMenuLaporanPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTMenuPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTMenuMobil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTMenuUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTMenuTransaksi)
                .addGap(6, 6, 6)
                .addComponent(BTMenuPengembalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTMenuLaporanPeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(BTLogout)
                .addGap(27, 27, 27))
        );

        DPMenuUtama.setLayer(menuUtamaBackground1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DPMenuUtamaLayout = new javax.swing.GroupLayout(DPMenuUtama);
        DPMenuUtama.setLayout(DPMenuUtamaLayout);
        DPMenuUtamaLayout.setHorizontalGroup(
            DPMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuUtamaBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        DPMenuUtamaLayout.setVerticalGroup(
            DPMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuUtamaBackground1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DPMenuUtama)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DPMenuUtama)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1155, 726));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTMenuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMenuPelangganActionPerformed
        // TODO add your handling code here:
        ViewPelanggan VP = new ViewPelanggan();
        this.DPMenuUtama.add(VP);
        VP.show();
    }//GEN-LAST:event_BTMenuPelangganActionPerformed

    private void BTMenuMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMenuMobilActionPerformed
        // TODO add your handling code here:
        ViewMobil VM = new ViewMobil();
        this.DPMenuUtama.add(VM);
        VM.show();
    }//GEN-LAST:event_BTMenuMobilActionPerformed

    private void BTMenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMenuTransaksiActionPerformed
        // TODO add your handling code here:
        ViewPeminjamanMobil VT = new ViewPeminjamanMobil();
        this.DPMenuUtama.add(VT);
        VT.show();
    }//GEN-LAST:event_BTMenuTransaksiActionPerformed

    private void BTMenuLaporanPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMenuLaporanPeminjamanActionPerformed
        // TODO add your handling code here:
        ViewLaporanPeminjaman laporan = new ViewLaporanPeminjaman();
        this.DPMenuUtama.add(laporan);
        laporan.show();
    }//GEN-LAST:event_BTMenuLaporanPeminjamanActionPerformed

    private void BTMenuPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMenuPengembalianActionPerformed
        // TODO add your handling code here:
        ViewPengembalianMobil pengembalian = new ViewPengembalianMobil();
        this.DPMenuUtama.add(pengembalian);
        pengembalian.show();
    }//GEN-LAST:event_BTMenuPengembalianActionPerformed

    private void BTMenuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMenuUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTMenuUserActionPerformed

    private void BTLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLogoutActionPerformed
        // TODO add your handling code here:
        ViewLogin login = new ViewLogin();
        login.setVisible(true);

        dispose();
    }//GEN-LAST:event_BTLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama_Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTLogout;
    private javax.swing.JButton BTMenuLaporanPeminjaman;
    private javax.swing.JButton BTMenuMobil;
    private javax.swing.JButton BTMenuPelanggan;
    private javax.swing.JButton BTMenuPengembalian;
    private javax.swing.JButton BTMenuTransaksi;
    private javax.swing.JButton BTMenuUser;
    private javax.swing.JDesktopPane DPMenuUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private background.MenuUtamaBackground menuUtamaBackground1;
    // End of variables declaration//GEN-END:variables
}
